Added Header Section
emmyobonyo/digital-business-card pull request #1
Opened 2022-02-04 17:30 UTC by emmyobonyo

### Tasks Completed
- Added display picture.
- Added profile details.
- Added relevant buttons.

#### I had a tough time with the buttons hence the long time. And also it was my first time working with Figma, so I had to learn how to be more detail-oriented., hence more time, but I'm learning.

2022-02-06 12:00 UTC, emmyobonyo commented
- I realized I should've created a new branch for the 'About section.' I guess it skipped my mind till it was a bit late.

2022-02-07 08:54 UTC, KnightWorker37 requested changes
And finally you can also include the editable Figma doc in case anyone wants to edit that in future? Is that even possible?

2022-02-07 08:54 UTC, KnightWorker37 commented on README.md
> -Open [http://localhost:3000](http://localhost:3000) to view it in your browser.
Not a bad idea to leave this in

2022-02-07 08:54 UTC, KnightWorker37 commented on public/index.html
> -    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
It was not necessary to delete this stuff. Actually going forward it's going to be kind of essential. Please read a bit more about PWA:

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps
https://web.dev/progressive-web-apps/

2022-02-07 08:54 UTC, KnightWorker37 commented on src/App.js
> +import About from './components/about/About';
Looking at the official recommendations: https://reactjs.org/docs/faq-structure.html

I guess it should be not be that nested? So either:

```suggestion
import Header from './header/Header';
import About from './about/About';
```
or:
```suggestion
import Header from './components/Header';
import About from './components/About';
```

What do you think?

2022-02-07 08:54 UTC, KnightWorker37 commented on src/components/Header.js
> +      <img src="./obonyo.jpeg" alt="Emmanuel Obonyo" />
It would be nice if all this displayed data could be extracted to input arguments to make it reusable?

2022-02-07 08:59 UTC, raybesiga commented
I believe that it is possible to share a Figma link @KnightWorker37 @emmyobonyo

2022-02-07 09:37 UTC, emmyobonyo commented on src/App.js
> +import About from './components/about/About';
Agreed. Thanks for the suggestion. Too much nesting is definitely not good in the long run.

2022-02-08 13:17 UTC, emmyobonyo commented on README.md
> -Open [http://localhost:3000](http://localhost:3000) to view it in your browser.
- Done ✅

2022-02-08 13:19 UTC, emmyobonyo commented on public/index.html
> -    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
- I've browsed through the documentation and it's actually very important. I'm going to start leaving them in my future apps.

2022-02-08 13:24 UTC, emmyobonyo commented on src/components/Header.js
> +      <img src="./obonyo.jpeg" alt="Emmanuel Obonyo" />
Noted.

2022-02-08 13:25 UTC, merged